### ISSUE TITLE
Allow increasing specificity based on utility order for same utility type

### ISSUE THREAD

**Issue by jd-solanki** [unocss/unocss#1165]
Hi 👋🏻 

I have demonstrated the query in this playground link: [view](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuBTAHpgWgCNlsod8CAmXOKIgcwLADtwGB7KAB1wIDYoACwIBGAAxRWcVtgIAzOHigAnDgFc22EATgN0APgqEacYAHpwEA0A&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

In above playground I applied `text-2xl` after `text-base` so I guess it should get higher specificity than `text-base`.

I can apply `!text-2xl` but I am building a component lib based on UnoCSS _(which I will reveal in next couple of days)_ and it adds extra classes passed by user at the end of class string. Generally, if user enters it's own class it should override previous one. But this is not the case here.

~~As a workaround I can loop over user class string and add prefix `!` but I just wanted to raise this issue if this is possible with UnoCSS I can omit looping over string each time for all components.~~
Above workaround will also add prefix to user custom classes which breaks styles so no workaround at the moment.

I really appericiate UnoCSS dev for hard work 😊

**Comment by chu121su12** [comment]
Currently there's no workaround this behaviour due to the way rules get sorted.

To prioritize rules, you may use `uno-layer-name:x`. Most likely, you'd want to **DE**prioritize your rules so the users' got to be the default

[Playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuBTAHpgWgCNlsoBXAOwHsDEBPbAJwPKWYJ3wICZc4oRAOYEwlcEOpQADrgIA2KAAsCARgAMUMXDHYCAMzh4oTalRDYQdIegB8XQnzjAA9OAi2AUJ9CRYiFAwqWgYOEnZOPEJwsgdefkERMQkpWQVlNU1tXQMjXBMzcUtrOzinV3cvTyA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&options=N4IgzgLgTglgxhEAuaBXApgXyA)
