### ISSUE TITLE
Again, when will this be production-ready?

### ISSUE THREAD

**Issue by 205g0** [unocss/unocss#121]
@antfu, apologies for opening again the same issue: Last time I asked was 3 weeks ago. And I just wonder what your actual goal is, being a part of Windi, letting Uno stand on its own (yes, I've read your blog post). We check out Unocss every here and then and would love to have a bit more direction and focus.

Means, when will it be production-ready, will you keep maintaining it for a long-term or was it just an angry shot at Tailwind and so on. The one blog post you keep linking is very nice but unfortunately doesn't help in these matters. I mean it's easy to write that your lib is 1000x better without being production ready. If you want to be a clear alternative to aforementioned users would love to have some more direction.

Is it ok to keep this issue open, as an issue, with the goal to get production-ready?

Looking forward to your response! 🙂

**Comment by antfu** [comment]
Thanks for bringing it up again. The statement is written in one month again when it has been released. At that time, UnoCSS is yes pretty much in experimental. During this one month of the time, if you can see, we worked really hard to bring a lot of fixes, enchancments and new features.

Just for FYI, we now support layers, made the Webpack plugin, Nuxt module, a Runtime CDN, the CLI, almost Tailwind compactible utilities. We have over 95% test coverage, we generate changelog, we follow semver to release internal breaking changes. TBH, this is almost the best we can do for an open-source project.

I know there are quite a few sites that already using it in production. As I mentioned in the blog post, you can already use it if you want to, as long as the future breaking changes are acceptable to you (technically breaking changes happen on any projects).

I would keep the experimental statement for a while longer, and there is no ETA for marking it "production-ready". As I want UnoCSS to provide the best if possible instead of rushing to be production-ready and freeze the API.

> Means, when will it be production-ready, will you keep maintaining it for a long-term or was it just an angry shot at Tailwind and so on. The one blog post you keep linking is very nice but unfortunately doesn't help in these matters. I mean it's easy to write that your lib is 1000x better without being production ready.

The "angry shot" word you picked reads rudely to me. I don't really care if you go Tailwind or UnoCSS or whatever, I didn't ask you to use UnoCSS either. Of course, I will keep maintaining it just like the other projects I have. But be sure that you are clear about what open source is, **there is no warranty and guarantee** to use an open-source project. Most of the maintainers spend their time maintaining projects for free is because they care about their projects but not any promise to the users. Consider showing some more respect or even sponsoring projects and maintainers to help the projects move forward next time.

Thanks.

**Comment by 205g0** [comment]
> The "angry shot" word you picked reads rudely to me.

I politely disagree, it's the elephant in the room everybody is wondering about and it's not about being disrespectful.

However and look, not everybody has the luxury just to put new libs into their projects. They have to justify, defend their decision in front of larger teams and show some proof that this lib has a future and not too many breaking changes are expected. So, I want to use your work but I need to do a due diligence. The questions I ask are the ones I get from my team. They just want to stick with Tailwind because they have mixed feelings about the new, the other maintainer and whatever. 

I find this normal and think nobody should feel hurt about a healthy debate. It gives you valuable feedback about your work, your communication and how to sharpen your profile, work, communication in future.

The same way around, this conversation and also that your emotions got affected by "angry shot" shows how you get triggered and if it is worth to build upon your work and potentially sponsor you at some point. And yes, you got a bit triggered but I found it ok, you didn't ban me or close the conversation, so all good here.

So, I appreciate your reply but have here and there a slightly different views (adding features is always easier than building a production-ready design) and need clarification on the "stability" of the project.

> Most of the maintainers spend their time maintaining projects for free 

Yes, I wholehearted  agree with you and OSS is the best which could happen to this world. But, people like you and other maintainers get valuable feedback from users and edge  use cases, they wouldn't get otherwise. High-starred repos give karma and easily +$500k salaries. A good repo is better than any cv haha. Just putting "free" into perspective.

Whatever, great work, thanks for your clarification and would like to see more of such posts in future from you, maybe as pinned?

let the community know where you need help, what needs to be done to reach production-readiness. If you don't achieve that milestones, no worries but sometimes it's good to have at least some short-term goals.

I hope I showed some respect this time, if not let me know, then, I'd try to improve!

🙂

**Comment by Codermar** [comment]
The original question is a valid but very poorly worded. It would be nice if @205g0 edits the original question and removes some of the offending stuff that's for sure out of place. When we run into a an open source and it has some very cool stuff like this one has, it is tempting to demand it to be ready for us (we're so used to instant gratification) and we don't realize it is a process that requires effort. Also, if you care as much, please put your money where your words are and support the open source developers involved! :-)

**Comment by axmad386** [comment]
Why people keep comparing other css framework with unocss. 
I came from native css, then learn a lot of css framework. All of them is cool, but you know, I still love native css, but it is time consuming. Unocss give me all I need. I can write my own rules, my own world. That's crazy. 
Can't wait this brilliant package to be production ready

**Comment by uma-uc** [comment]
Hi everyone,

Thanks for this awesome package. We are using this in the context for cite and solid-js. It takes a very long time to load.
We have the following presets:

- presetIcons
- presetWindi 

It is me - or others also having this issue?

**Comment by antfu** [comment]
@uma-uc Can't help without a proper reproduction. And please create a separate issue to track it.

**Comment by millette** [comment]
@uma-uc I too use it with solidjs and find it's very fast.

-    "@unocss/preset-wind": "0.22.4"
-    "@unocss/reset": "0.22.4"
-    "unocss": "0.22.4"

_(Not using icons)_

Sorry for the off-topic noise

**Comment by rubiin** [comment]
I have switched from tailwind to unocss in some of my projects with no problems till now. Its production ready if you ask me. @antfu how about an issue to list out who uses unocss. That would help people with questions of this sort and also help them switch looking at the numbers and projects using it
