### ISSUE TITLE
custom color invalid

### ISSUE THREAD

**Issue by pengyinghao** [unocss/unocss#1282]
[address](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIYFoAOAnMAWwTwE90A%2BAKCgAsBTOOAeyiuAHpwJrRJZEKDNnxESpLHDABzWgBcAjJRoMmrdl0gUgA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyMFUYIBjBzQCQ2dCNJ8LsIPZQ-MF6E1NpsnDHqHo0oLf8g95VMAAjD19BwnFw0lRjmoqNsqCIFI1wpE5KIlCofABKV6ohQsNicHh8fhYnEI8RSXB0Pwo1B0CTrQ5wQEAOgATDjUBI0Lg8gCYGBGgB6IX0EAs6pCzYtNTY8pIWVIIA&options=N4XyA)

**Comment by chu121su12** [comment]
Due to the way color token get parsed, your config should be like this
```js
primary: {
  DEFAULT: 'orange',
  light: {
    1: 'blue',
  },
},
```

https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIYFoAOAnMAWwTwE90A%2BAKCgAsBTOOAeyiuAHpwJrRJZEKDNnxESpLHDABzWgBcAjJRoMmrdl0gUgA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyMFUYIBjBzQCQ2dCNzS1yoPZQ-E2RV3AAIgCiAGJMigAyACp5EymaVkTzgTm8VRgD1BVwAjHkOE4uMDHldtqjirJjmoqOjhPJGI1wo8RAplBAfABKEFyUTMVjsbi8ARUmmk8RSXB0PwYugSdaHOCwgB0ACYaagJGhcHlITAwI0APSK%2BggYXVRWbFpqanlJA6pBAA&options=N4XyA

**Comment by pengyinghao** [comment]
thank
