### ISSUE TITLE
Would you might add a new package for converting px to vw ?

### ISSUE THREAD

**Issue by Craig-Cheng** [unocss/unocss#1368]
i had tried to add a new repository, but i found that your package depend to the root project -- unocss.
Would you might add a new package for converting px to vw, plz ?

**_For example(edit from your package: @unocss/preset-rem-to-px):_** 
```javascript
import type { Preset } from '@unocss/core';

const pxRE = /^-?[\.\d]+px$/;

export interface PxToVwOptions {
    /**
     * 1px = 1/3.75 vw
     * @default 3.75
     */
    baseDivisor?: number;
}

export default function PxToVwPreset(options: PxToVwOptions = {}): Preset {
    const { baseDivisor = 3.75 } = options;

    return {
        name: '@unocss/preset-px-to-vw',
        postprocess: (util) => {
            util.entries.forEach((i) => {
                const value = i[1];
                if (value && typeof value === 'string' && pxRE.test(value)) i[1] = `${+value.slice(0, -3) / baseDivisor}vw`;
            });
        },
    };
}


```

Looking forward to your reply ~

**Comment by antfu** [comment]
I am afraid that does not make sense in general usage. e.g. `h-100px`

`@unocss/preset-rem-to-px` is more serving as a demo for such cases. Since it's not complicated, I'd suggest you inline the implementation for your specific case.

**Comment by weirui88888** [comment]
> ```js
>  baseDivisor?: number;
> ```

i am a newer about unocss,I want to use unocss in the mobile webpage, but I want to convert the rem unit to vw, because it is convenient for me to develop responsively, so I implemented a preset-rem-to by referring to your preset-rem-to-px -vw, the content is as follows, please help me take a look, is this okay?

![image](https://github.com/unocss/unocss/assets/23164664/aefb8510-e467-4554-bbb0-2d272e27ec71)
