### ISSUE TITLE
`` Error

### ISSUE THREAD

**Issue by qiaer** [unocss/unocss#1406]
Using template strings will be scanned, and illegal characters will be generated after escaping, resulting in a compilation error.

![image](https://user-images.githubusercontent.com/24616514/184325093-b5af2f2b-33cb-410f-850d-29c5a50869ec.png)

![image](https://user-images.githubusercontent.com/24616514/184325131-c5f05062-9cae-48c8-b89b-2deb31f124b5.png)

**Comment by chu121su12** [comment]
This is expected due to this rule:

https://github.com/unocss/unocss/blob/5df9f7f9b8aaf1e3949712e31cc54668b53da269/packages/preset-mini/src/rules/variables.ts#L28-L30

You may want to add some tokens into the blocklist; or am I missing something?

[Playground](https://uno.antfu.me/play/?html=AYbQrgDgNg9ghgEwJYDsDmAuAJAbxXAWwFMBfAXWAChRJZFVNcAjWAYwGtyqg&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAqrhJQL5xZQQhwDkAV1YBjOnX5IkGAB6RY6bAENBAG3iYc%2BIiWCkAFMlQ16jOgC44AbSrHaDZq30BKSqgC6buACNVEEQDWqsB0MJZW-FaCYH5KaHik5gAkCL7%2BAezu-J5I7M5IQA&options=N4IgzgLgTglgxhEAuaBXApgXyA)
