### ISSUE TITLE
how to custom icons add

### ISSUE THREAD

**Issue by productdevbook** [unocss/unocss#147]
https://github.com/antfu/unocss/tree/main/packages/preset-icons dont see settings

**Comment by itpropro** [comment]
Good question, what would be the preferred way to import custom svg icons @antfu? Do we have to add unplugin-icons, add a custom unocss preset or is there any easy way to extend the icon set for the pure css icon logic?

**Comment by userquin** [comment]
@itpropro we are working to include a universal icon loader on `@iconify` and so we can use it here and on `unplugin-icons`. 

We dont want to include the same logic twice.

The way to add custom icons will be the same like on `unplugin-icons`.

**Comment by userquin** [comment]
We've included the universal icon loader on `@iconify` but we need to change a few things since `unocss` can use it also on client side, while on `unplugin-icons` it is used only on node.

**Comment by itpropro** [comment]
Hey @userquin, I saw all the great work you did to unocss since I checked it out a few month ago and I just wanted to ask if something has changed, as I only found this PR https://github.com/unocss/unocss/pull/730 digging through the recent code changes.
If you could point me a direction whats you recommended way to use unplugin-icons as a temporary alternative it would already help a lot :)

**Comment by userquin** [comment]
@itpropro see this https://github.com/antfu/unplugin-icons#icon-customizer, in the `customCollections` option you have 3 ways to load icons: accessing the filesystem, using `fecth` or using `FileSystemIconResolver ` (you can also have the literal svg). At the end of the section you have how to use the icons.

Beware, the approach in `unplugin-icons` is to resolve icons always on the server: when #730 is merged, it will have the same behavior here, and you will be able to use it in the browser as well (except file system access)

**Comment by itpropro** [comment]
Hi @userquin thanks for your reply! Are you referring to use unplugin-icons as a workaround and disabling `presetIcons` until the PR is done or is there a way to use these methods to create the `IconifyJSON` object, needed in the `collections` property of the `presetIcons` settings?

**Comment by userquin** [comment]
> Hi @userquin thanks for your reply! Are you referring to use unplugin-icons as a workaround and disabling `presetIcons` until the PR is done or is there a way to use these methods to create the `IconifyJSON` object, needed in the `collections` property of the `presetIcons` settings?

You were asking about using `unplugin-icons`, so the answer is yes, disable the `preset icons` and add the `unplugin-icons` (should also work with both). 
Before disabling the `preset icons` or adding the `unplugin-icons`, you can also try resolving the `iconify` collections via `dynamic import`, it should also work: keep in mind when #730 is merged, there will be a small breaking change since the `collections` option signature will change, but you can solve it using the `FileSystemIconLoader` from `@iconify/utils/lib/loader/node-loaders`.

I'll try to add also a `FileSystemIconLoader` here, wrapping the `iconify` one like on `unplugin-icons`.

**Comment by itpropro** [comment]
Thanks for clarifying, looking forward to the PR, and will be using `unplugin-icons` in the meantime :)
