### ISSUE TITLE
Include classes from external package

### ISSUE THREAD

**Issue by praburangki** [unocss/unocss#1746]
This could be related to #1336 & #1569 , but I've added a reproduction repo:

https://github.com/praburangki/unocss-scan-reproduce

The main goal is to make unocss read the classes that are defined within the external library.
Could this be specific within nuxt?

**Comment by danielwaltz** [comment]
I'm also curious about support for this feature! In my case I am using Prime UI and would like to dynamically load only the icons I want using UnoCSS instead of loading the entire collection of icons that Prime provides.

I have already figured out a shortcut to rewrite `pi-` prefixed icons to `i-prime-`, but now I would like this to apply to components imported from Prime itself.

**Comment by danielwaltz** [comment]
I found a solution to this myself! You can use the `include` option to have `unocss` watch for any files loaded via `vite` using regex. In my case, in order to have `unocss` scan `primereact` components, I added the following to my unocss config:

```ts
{
  include: [/(.*\/)primereact(.*)\.(c|m)?(js)(x?)$/, '**/*.{ts,tsx}']
}
```

You can of course adapt that regex to your use case by modifying it however you see fit, and you can check your browser's dev tools in the network tab to verify the regex matches on the format of the file names `vite` is serving from the external library. This is important because if you try matching on files using your local file system it won't work, `unocss` only scans files that are being served by `vite` to the browser. It's also important to make sure you explicitly include your project files as they are not inherited when defining the include option yourself, as I've done with the second entry in the include array.

Anthony might be able to clarify some points as some of my explanation is by observation without digging into the code myself!

**Comment by sherif414** [comment]
> 

thanks, the classes are generated at dev but not at build time. have you encountered this issue?

**Comment by jbaubree** [comment]
@sherif414 you may need to include classes from `node_modules/.vite/...` in dev mode and `node_modules/.pnpm/...` in build mode

**Comment by siduck** [comment]
@jbaubree  could you show some code?
