### ISSUE TITLE
transformer-compile-class requires full vite server restart for changes

### ISSUE THREAD

**Issue by cpakken** [unocss/unocss#1761]
https://github.com/unocss/unocss/tree/main/packages/transformer-compile-class/

The compile class transformer requires a full vite server restart for changes to occur. HMR and page refresh does not work

i.e. changing
```<div className=":uno: bg-red w-100 h-100">```
to
```<div className=":uno: bg-blue-100 h-100">```

**Comment by euwei9** [comment]
The reason why it's not working is because unocss executed a reload, but did not restart the transformer, which resulted in all shortcuts configuration previously processed by the transformer being lost. You can check the output result by using `console.log(unocss.uno.config.shortcuts)` on the onReload callback to understand why it's not working. Hopefully, the official team can fix this issue.
