### ISSUE TITLE
`[&[data-[state=open]]>span]:rotate-180` doesnot work

### ISSUE THREAD

**Issue by zouhangwithsweet** [unocss/unocss#2249]
### UnoCSS version

0.50.0

### Describe the bug

`[&[data-[state=open]]>span]:rotate-180` doesnot work

### Reproduction

https://uno.antfu.me/play/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq6XU6ED26AzltQfsQ8VlAIZoAXBjJ9izMBjDc4AFgAM8qAG0AZMpB8MfOMubbsAXgYAHEgF1zAPmYmx5wWQYGscAIwAOeVYBQUKKCQUAC2fL7%2B-oHQImLMCAxkwXAA5iZImLj4AKw46AgA7m6K-MRgodhwAEYMSMREcAIYJWVargQ1pHBgxAjdkrxiLRUgSKJSMm7M4RH%2BtQwEzMx%2BEcAA9OAQ05EbUKYAzErYeHAoyZT5B0rBblAEKHyLhgBEDCAgwplwZFggT1sRABUYLxuvoxE0ZCAsKFiCAoABBDAMYJgAhQADCAGVMVASMlulgAHQ%2BZaRdaQf5REIAJloNAAVkh9GAEABPQgkcgZY7U3K7EwHWAMCBYMjPUxeP6klZ8aUzMCEPhkarEE4MZIMFKSGBISpyiJHfDdYFkST6-wwb4IZ4wDAYEzMQSrVb4jA6yqE9rBVZzBbMH1cP1Pc2YJXJLAYZ4AfUq92IAGtgzN-FY1mFpWsNtNMxSfDnNnmdnxKswmEhsFBqnbkXAslBTclbXAlNQEPhDp8iKRRfzBQVLtNIdCxHCAO1QUHaUhQcfINCs25MpEogBexeoefJmyAA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sibbng** [comment]
You can use that arbitrary variant as a attributify selector since it contains `=`. Use it as a class instead. And you don't need to wrap state=open with brackets.

https://uno.antfu.me/play/?html=DwEwlgbgBCCGAusC0BnR8CmBeARAewAcMA7HKAYwBtYUVcBtAMnrkVXW0JIF0A%2BFArGLcAXACMA5kgBOGEDl4AoYAKG8aIYAHpVxJdvAReQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA
