### ISSUE TITLE
Feature request: add compatibility for svelte-multicssclass to enable usage of multiple classes in a single class directive in svelte scoped mode

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [unocss/unocss#2322]
### Clear and concise description of the problem

It would be nice if UnoCSS could work together with svelte-multicssclass which is a plugin to enable usage of multiple classes separated by a separator character in a class directive, so for example `class:bg-blue-500|hover:bg-blue-300={!red}`

Right now it doesn't really work. On first load it works but when HMR kicks in the extra classes are removed.

Repro: https://stackblitz.com/edit/unocss-unocss-cbyaza?file=src/routes/+page.svelte

It works after loading but after typing anything in +page.svelte (for example) the classes get removed.

### Suggested solution

No idea of how to implement it or if it is possible, but since it works when loading the first time maybe it could be implemented.

Or maybe it could be implemented as a native feature in svelte-scoped which would be even better.

### Alternative

To simply not use svelte-multicssclass but it would be pretty cool if it worked!

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jacob-8** [comment]
I'm still undecided if this should be a native feature in `svelte-scoped` since [svelte-multiclass](svelte-multicssclass) has already addressed it. We can think more about it post #2552 as making it native would require much less code than that required by https://github.com/fernandolguevara/svelte-multicssclass/blob/main/src/plugin.ts as their solution is general purpose.

My main concern would be not introducing any breaking syntax for tooling. An initial [test](https://svelte.dev/repl/487f03bfd5b14eea9f83e3ed2987257e?version=3.58.0) seems to indicate the pipe `|` is friendly to the Svelte parser:
![image](https://user-images.githubusercontent.com/7559478/235107136-f2bdf819-b9ff-4899-9738-f337cd274fcf.png)

Related: https://github.com/sveltejs/svelte/issues/7170

In the meantime though, why don't you try creating a PR to solve https://github.com/fernandolguevara/svelte-multicssclass/issues/2 that I posted about your HMR problem. I didn't test the code I posted in there but it should give you what you're looking for.

**Comment by fernandolguevara** [comment]
@henrikvilhelmberglund svelte-multicssclass 2.1.1 is out, can u try hmr now?

@jacob-8 thanks 🚀

**Comment by jacob-8** [comment]
@henrikvilhelmberglund is this still a request? How are you finding `svelte-multicssclass` as a solution to your problem. I'm still chewing on if we want to add this. As well, are there others who want this?

**Comment by henrikvilhelmberglund** [comment]
svelte-multicssclass works fine. The original request was just for it to work together with UnoCSS so I'll close this as it works now.
