### ISSUE TITLE
[vscode] syntax decoration broken in v0.50.7

### ISSUE THREAD

**Issue by cuebit** [unocss/unocss#2460]
### UnoCSS version

0.50.7

### Describe the bug

Syntax decoration appears in the wrong place, making it difficult to accurately display tooltips, etc.

Vue SFC template example:

![v0 50 7](https://user-images.githubusercontent.com/1493221/230669359-844a4b48-012e-4941-8371-2d99ca8b5b99.png)

Vue SFC style example:

![v0 50 7-style](https://user-images.githubusercontent.com/1493221/230671418-589b67c2-2350-4282-938a-99ea01dde6b0.png)

### Reproduction

Install v0.50.7 and observe incorrect syntax decoration:

![v0 50 7](https://user-images.githubusercontent.com/1493221/230669411-1b1ee349-3293-4b8e-8b0f-79ff4541e145.png)

Rollback to v0.50.6 and observe correct syntax decoration:

![v0 50 6](https://user-images.githubusercontent.com/1493221/230669478-d3a1b4f3-258d-4c66-ab6e-dd835f72b0cb.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sibbng** [comment]
[Playground](https://uno.antfu.me/play/?html=IYZwJgXAUARu0GN6wZKUA8BlAkgg9gHZQAEJhwAtgKYC8ARADYAuAThAO4C0AZgK6NGJVs0adeAxvVIkEjUCAYBCYIwCWAc0JdKasGEbVpAegB8MoA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&css=HQSwdmCmBOBcsEMBmAXGBvAUAAmwYwHsw1jZsByAFgFYA2cgbkwF8g&options=N4XyA)

Highligting starting to shift as words ending with `:` increases. Probably caused by https://github.com/unocss/unocss/commit/f27b1fd3a1557808f35281c5f4bf601ca7422904
