### ISSUE TITLE
`shadow` not producing `box-shadow` in SvelteKIT scoped mode

### ISSUE THREAD

**Issue by ptrxyz** [unocss/unocss#2629]
### UnoCSS version

0.51.13

### Describe the bug

When using `class="shadow shadow-black` and variants (`-lg`, `-md`, etc) a box-shadow is not produced.
I am using SvelteKit with the scope-extraction method.

Using the web developer tools inspecting the HTML shows that some styles are generated but some variables being undefined (`--un-shaod-inset) leading to `--un-shadow` being undefined and thus no box shadow being generated:

**Styles:**
![image](https://github.com/unocss/unocss/assets/209056/a6a0cf73-05dd-47bc-a2b4-5b7e2821aa5a)

**Computed Styles:**
![image](https://github.com/unocss/unocss/assets/209056/cb04e970-0172-4a68-b176-4fab629ec90e)

### Reproduction

Use the SvelteKit example template and add `shadow` to one of the divs.
Use this Stackblitz link: https://stackblitz.com/edit/unocss-unocss-uwkajm?file=src%2Froutes%2F%2Bpage.svelte%3AL21

Edit: This seems to only be present in the SvelteKit-scoped example, SvelteKit with extractor seems to work.
### System Info

Linux, Chrome, SvelteKit (scoped)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jacob-8** [comment]
This is due to a lack of preflights. The previous preflights solution for svelte-scoped was never fully-baked and in successive upgrades on the Svelte side at some point the `Preflights` component became useless because all the preflights get stripped out. Note the warning notice in your repro:

> [vite-plugin-svelte] /src/routes/Preflights.svelte:2:1 No scopable elements found in template. If you're using global styles in the style tag, you should move it into an external stylesheet file and import it in JS. See https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#where-should-i-put-my-global-styles.

The quick solution is to look at the default Uno preflights 

--un-shadow-inset: ;
--un-ring-offset-shadow: 0 0 rgba(0, 0, 0, 0);
--un-ring-shadow: 0 0 rgba(0, 0, 0, 0);

You can always check out preflights by going to the playground. In this case you can go to this [playground](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIkAsEgPYDuAtHAOZQC2RArFAEZ4BOIApo%2BgHwASLccewAPTgIHIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&css=Q&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBoQJ84AHJeASwDd9Ns98BfIA), make sure your in light mode, and then in the Output CSS check the `preflights` box to have a look around.

But there are other classes that depend on other preflights, so you should probably include them all until you understand each better. _I myself am working towards understanding the preflights system._

For an up to date solution, you can use the latest version of svelte-scoped which can be found at https://github.com/jacob-8/svelte-scoped-uno or wait until #2552 is merged. Both are the same code, though the merge is pending review and any additional improvements/adjustments that may be needed.

**Comment by henrikvilhelmberglund** [comment]
I'm using the latest svelte-scoped but `uno:preflights` still doesn't work for me (I'm using the preprocessor)...

**Comment by jacob-8** [comment]
> I'm using the latest svelte-scoped but `uno:preflights` still doesn't work for me (I'm using the preprocessor)...

@henrikvilhelmberglund can you start with the stackblitz example for the preprocessor and create an issue with a minimal repro please?
