### ISSUE TITLE
Svelte-Scoped & Dynamic Class limitations (safelist)

### ISSUE THREAD

**Issue by JohnnyMcWeed** [unocss/unocss#2745]
### UnoCSS version

0.53.1

### Describe the bug

It seems the dynamic CSS generation is currently having issues and I'm not aware of any workaround according to the docs.
Safelist approach is having a bug (see point 2 mentioned below)

The reproductions link shows the following:
1.) Fixed result possibilities (without layout change)
The two layouts that should be achieved.
2.) Dynamic class / Safelist approach
(Safelist must be reenabled in the example. This caused issues with the other styles when enabled -> Bug)
3.) Class attribute approach
(This is causing issues when having something like "sm:basis-1/2" which will not work.)

### Reproduction

https://stackblitz.com/edit/unocss-unocss-w4tud7

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jacob-8** [comment]
You can accomplish what you'd like by using a class expression with % instead of a fraction, `class:sm:basis-50%={!grid}` as seen in https://stackblitz.com/edit/unocss-unocss-pqv7fv?file=src%2Froutes%2F%2Bpage.svelte Compare https://unocss.dev/interactive/?s=sm:basis-1/2 with https://unocss.dev/interactive/?s=sm:basis-50%.

And yes, as you pointed out the safelist approach is prone to quirks if you are not aware of the ordering situation. Safelist classes come first, followed by component scoped classes. I think you'll find that class expressions solve all of the use cases shown in your repro.

**Comment by jacob-8** [comment]
I wanted to add also that your syntax is not supported:
```
class={`grid grid-cols-1 ${gridClasses} gap-4`}
```

That sort of thing would be written as `class="grid grid-cols-1 {gridClasses} gap-4"`. See [supported syntax](https://unocss.dev/integrations/svelte-scoped#usage). String interpolation is not needed inside the template html and makes Svelte harder to read.

**Comment by JohnnyMcWeed** [comment]
All right, thanks for the explanation
