### ISSUE TITLE
Events like `on:click` don't work with Safari + SvelteKit + Regular Vite plugin + Attributify mode

### ISSUE THREAD

**Issue by Charliego3** [unocss/unocss#2791]
### UnoCSS version

0.53.3

### Describe the bug

The same program works well on Chrome, but events such as "on:click" are not responsive on Safari.

### Reproduction

This is a minimal implementation.
https://stackblitz.com/edit/unocss-attributify?file=src%2Froutes%2F%2Bpage.svelte

### System Info

macOS: Ventura 13.3.1
Safari: 16.4
Chrome: 114.0.5735.133

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jacob-8** [comment]
A Mac will be needed for whoever wants to look further into this. @Charliego3 can you make a more minimal example in the meantime, please? Just a button with some attributify classes which then breaks the functionality. Remove everything else from your uno.config.ts that's not part of the bug, so that would be just `presetUno(), presetAttributify()`. Also, note the `hooks.server.js` file is not needed when using the regular Vite plugin as you are doing.

**Comment by Charliego3** [comment]
Here is a minimal implementation: [UnoCSS Sveltekit Safari Demo with Stackblitz](https://stackblitz.com/edit/stackblitz-starters-1muub6?file=uno.config.ts).
The button event will not respond when it is opened for the first time, it will respond normally after removing `import 'uno.css' in `+layout.svelte`, but the style is missing, and it can work normally after importing `import 'uno.css'` again

**Comment by jacob-8** [comment]
Thanks. Someone with a Mac can try to help debug for you, I don't have one. In the meantime, see if you can't isolate which style inside your `uno.css` is causing the Safari conflict. Try removing them one by one. Also, see if toggling attributify mode makes any difference.

Also you don't have a styles reset. Do you normally develop without a reset? Does Safari need a reset to play nice? I'm clueless about this because I always use a reset and I don't use Safari.

**Comment by Charliego3** [comment]
I have this problem on both Macs. Try to close the `Attributify Mode`, introduce `TailWind` reset, and finally the same results. It can be run well on Chrome, so I don't know why. I don’t know if anyone encountered this problem like me. 😢

**Comment by jacob-8** [comment]
> finally the same results

The next thing is to open the devtools in Safari and remove all added Uno styles one by one to see if you can find what is breaking the button. The idea is to remove piece by piece until Uno is completely gone. Assuming the problem is with Uno and not just a Safari+Sveltekit issue, you should eventually find the problem.

**Comment by Charliego3** [comment]
When using SvelteKit alone, everything runs fine on Safari. Also, when using Tailwind CSS, everything works well. Currently the issue only occurs when using UnoCSS. 
When using UnoCSS, there are two errors that occur when loading the page.
<img width="1186" alt="image" src="https://github.com/unocss/unocss/assets/26761592/cefb9f19-2b1e-4414-a1aa-387bdf77a7b3">
<img width="999" alt="image" src="https://github.com/unocss/unocss/assets/26761592/a0917011-eac6-41ac-bf0b-7411358f5ace">
<img width="1115" alt="image" src="https://github.com/unocss/unocss/assets/26761592/3e6d3b58-7782-4657-b992-102013b3bef3">
Since I don't have this error when using TailwindCSS, I'm not sure if it's a problem with UnoCSS, I can only put forward the problems I encountered.

**Comment by mustevenplay** [comment]
This is happening to me too.
