### ISSUE TITLE
How to listen for class in node_modules dependencies?

### ISSUE THREAD

**Issue by dufu1991** [unocss/unocss#2912]
### UnoCSS version

0.50.6

### Describe the bug

I used Vite + Svelte to create a project that is going to use a UI component library, [STDF](https://github.com/dufu1991/stdf), whose components are written according to Tailwind rules. 
Now I want to use UnoCSS in my project with the preset of Tailwind, but UnoCSS does not compile the files in node_modules, and the [document](https://unocss.dev/guide/extracting) here is not explained. 
In this case, how should I configure UnoCSS so that it can handle files specified in node_modules. You can implement a content configuration similar to that in tailwind.config.js in Tailwind.

---

我使用 Vite + Svelte 创建了一个项目，准备使用一个 UI 组件库 [STDF](https://github.com/dufu1991/stdf)，这个 NPM 里面的组件是按照 Tailwind 的规则写的。
现在我想在项目中使用 UnoCSS 配合 Tailwind 的预设，但是 UnoCSS 不会编译 node_modules 里面的文件，这里的[文档](https://unocss.dev/guide/extracting) 也没有说明。
此种情况我应该如何配置 UnoCSS 使其可以处理 node_modules 里指定文件。可以实现类似 Tailwind 中 tailwind.config.js 中的 content 配置。

### Reproduction

Go to [Stackblitz](https://stackblitz.com/edit/vitejs-vite-9yc75c)

In this project, the CSS in the src/App.svelte is valid, but the one in the node_modules STDF component is not. How should I configure it?

---

这个工程中，src/App.svelte 内的 CSS 是生效的，node_modules 内STDF 组件内的没生效，我该如何配置？

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vonagam** [comment]
I just had the same problem with using `flowbite-svelte`. Here are three potential solutions for those who stumble here, not all of them are applicable to every situation.

#### `content.filesystem`

Use that option in unocss config to add all types from a library. For example for flowbite it would be something like that:
```js
export default defineConfig({
  content: {
    filesystem: [
      './node_modules/flowbite-svelte/dist/*/*.svelte',
    ],
  },
  // ...
});
```

Cons: it will include all classes from all components, not only ones that you use, and I don't think it is compatible with yarn.

#### prebundleSvelteLibraries

Set [that option](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#prebundlesveltelibraries) to false in vite svelte plugin. The real problem is that svelte plugin modifies config and puts `.svelte` dependencies into `optimizeDeps.extensions`, so unocss pipeline never receives `.svelte` content only compiled files with `.js` extension (which is not part of default `pipeline.include` regexp).

```js
export default defineConfig({
  plugins: [
    UnocssPlugin(), // unocss plugin should be before svelte by the way
    SveltePlugin({prebundleSvelteLibraries: false}),
  ],
  // ...
});
```  

Cons: it will slow down compilation, I have not experimented with this much, don't know if the slowdown applies only to initial render or consequent ones too. (If it is only initial one, then it is not that bad.)

#### content.pipleline.include

If you can figure out the pattern for filenames to which vite precompiles svelte files, you can add that pattern to pipeline. On my machine vite was generating `__svelte.js` files for flowbite (in `node_modules/.vite/deps`): 
```js
export default defineConfig({
  content: {
    pipeline: {
      include: [
        /\.(vue|svelte|[jt]sx|mdx?|astro|elm|php|phtml|html)($|\?)/, // copy default
        /__svelte\.js($|\?)/,
      ],
    },
  },
  // ...
})
```

Cons: `prebundleSvelteLibraries: false` has worked with your stackblitz but including `__svelte.js` in pipeline did not, so that pattern might not be universal.

**Comment by dufu1991** [comment]
oh, I see [Chinese document](https://unocss.dev/guide/extracting), not [English document](https://unocss.dev/guide/extracting), so have not **Extracting from Build Tools Pipeline** ,it is my problem!
Thank you very much 🙏🏻🙏🏻🙏🏻
