### ISSUE TITLE
Strange phenomenon | Refresh the browser, the style will be temporarily invalid.

### ISSUE THREAD

**Issue by yayxs** [unocss/unocss#3324]
### UnoCSS version

"unocss": "^0.57.1"

### Describe the bug

When I read the guide section of the documentation and the vite integration

Simple use, when I refresh the browser, the style has changed,I'm not sure if this is a normal effect
![image](https://github.com/unocss/unocss/assets/50107464/f8eb8a99-6e8c-4680-9dcc-f68e6e7a92c7)
When the style is not loaded, it is
![image](https://github.com/unocss/unocss/assets/50107464/c617b6be-02fc-426f-9436-4641de3e6c1c)

### use

```sh
index.html
main.js
vite.config.ts

# in main.js
import 'virtual:uno.css'

# in index.html

<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>use uno</title>
    <style>
      * {
        box-sizing: border-box;
      }
    </style>
  </head>
  <body>
    <script src="./main.js" type="module"></script>
    <span class="m-7">hello</span>
    <span class="m-7">uno</span>
  </body>
</html>

```

### Reproduction

[You can look here](https://github.com/yayxs/css-learn/tree/main/packages/unocss)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
Why don’t you refer to the official examples to implement it? https://github.com/unocss/unocss/tree/main/examples

**Comment by henrikvilhelmberglund** [comment]
This is called FOUC (flash of unstyled content) and is expected because it takes a while for your HTML page to load the .js file. Normally you use UnoCSS with some kind of framework that takes care of such issues. In your case you can do something similar to the runtime config:

- Add this in your index.html style tag: 
      .un-cloak {
        display: none;
      }
- Add the class to the <body> tag: <body class="un-cloak">
- Add this rule: ['un-cloak', { display: 'block' }]

This is just something I came up with right now so not sure if it's the best solution. It will hide everything in the body until UnoCSS kicks in and applies the rule that you defined in the config.
