### ISSUE TITLE
[Bug?] Mdc extractor not working

### ISSUE THREAD

**Issue by zdv1g** [unocss/unocss#3462]
### UnoCSS version

0.58

### Describe the bug

If using slug pages, extractor does not parse classes.

### Reproduction

[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/github-hmakaz?file=content%2Findex.md)

### System Info

Win x64
Brave 1.61
Nuxt 3.9
Nuxt-content 3.10

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
This is because the `content` folder is not going through the build-pipeline (there is an internal content layer in @nuxt/content), so the Vite plugin are not aware of it. You will need to explicit set `content.filesystem` to have UnoCSS scan those files: https://unocss.dev/guide/extracting#extracting-from-filesystem

**Comment by antfu** [comment]
https://stackblitz.com/edit/github-hmakaz-vtnzd5?file=uno.config.ts
