### ISSUE TITLE
Unocss seems to extractor the content from node_modules by default

### ISSUE THREAD

**Issue by xxf5530** [unocss/unocss#3514]
### UnoCSS version

0.58.3

### Describe the bug

I'm using unocss in [vitepress](https://github.com/vuejs/vitepress), and vitepress has its own default theme.

I find that even if I don't write anything, 
the packaged CSS file will contain some unnecessary styles (they are generated by unocss but I didn't declare).

By reading the documentation: [unocss.dev#extracting-from-build-tools-pipeline](https://unocss.dev/guide/extracting#extracting-from-build-tools-pipeline), 
I can manually configure the scan scope to avoid this problem.

My puzzle is why unocss scans vue file styles from node_modules by default.

### Reproduction

[stackblitz.com](https://stackblitz.com/edit/vite-edkr9p?file=docs%2F.vitepress%2Fdist%2Fassets%2Fstyle.rSm3uyae.css)

run `npm run docs:build`, and then found the css file in the dist folder.

e.g.  `container` is a style class declared in the vitepress theme, and is not declared locally (except node_modules).
![image](https://github.com/unocss/unocss/assets/154851198/572a0465-6516-4e42-a01a-2fc6eead0dc2)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
This is not caused by unocss. It seems to be due to a problem with the theme of vitepress. It may be caused by vitepress introducing content related to unocss. I think the issue should be raised to vitepress.

When I removed the theme related settings, the final style result was correct, only the initial style remained
<img width="424" alt="image" src="https://github.com/unocss/unocss/assets/57086651/d3dc6c48-ee01-4149-b649-f67122edccfe">
<img width="956" alt="image" src="https://github.com/unocss/unocss/assets/57086651/7575f432-db68-48f4-b9ab-53cb6b4aabc7">
