### ISSUE TITLE
Let `preflight-base` variables be generated on-demand and reusable.

### ISSUE THREAD

**Issue by LoTwT** [unocss/unocss#3521]
### Clear and concise description of the problem

The previous context in a discussion: <https://github.com/unocss/unocss/discussions/3513>.

Currently, UnoCSS will generate `preflight-base` variables as the default behavior with the `preset-mini`.

When building in the default mode `global`  without any utility, some `preflight-base` variables will always be generated to avoid potential errors in case of the usage of some utilities. However, the project doesn't always use some of these utilities. It may increase some extra computational and transferring costs.

In the modes such as `vue-scoped`, `shadow-dom`, and `dist-chunk`, these variables will be generated into each generated CSS file. It seems to be an unexpected behavior. Also in the mode `vue-scoped`, the selectors have a hash.

I haven't been using Svelte, so I don't know what the mode `svelte-scoped` behaves like.

### Suggested solution

The scopes may include:

- generate `preflight-base` variables on-demand when related utilities are in use
- clarify the modes in which these variables should be included in each generated CSS file and if they should be hashed in selectors
- how to reuse these variables in different CSS files

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jacob-8** [comment]
> I haven't been using Svelte, so I don't know what the mode `svelte-scoped` behaves like.

Not speaking to the issue as a whole, but just mentioning that the recommended way to use `svelte-scoped` [helps you load in a small amount of global styles](https://unocss.dev/integrations/svelte-scoped#global-styles) before any component styles are loaded. This includes preflights for sure but also safelist and reset if users have those. So there's no annoyance caused by having preflights generated in every file.

**Comment by Yves852** [comment]
Trying the mode 'vue-scoped' aswel in a test repository with Nuxt. By using 2 pages witth 4 components (2 being prefixed Lazy) I'm getting these chunks of code duplicated in each files and duplicated twice in some files.

![image](https://github.com/unocss/unocss/assets/86199387/1cd19aeb-3979-4ee7-a533-c06cec9b94dc)

Repro: https://stackblitz.com/~/github.com/Yves852/test-unocss-scope-nuxt

I didn't tried it in a real project yet to see what happens.

**Comment by Yves852** [comment]
On the project I work on for my job since 2022:

Build with default mode: generates 26 css files, total of **~250.5 KB (entry.css 235.4 KB)**
Build with vue-scoped mode: generates 212 files, total of **~12.4 MB (entry.css 1.7 MB)**

The substring `{--un-rotate:0;--un-rotate-x:0;` was duplicated in the entry.css file **72 times**.

![image](https://github.com/unocss/unocss/assets/86199387/fe82ba39-42c8-4b67-b6ea-f590fd18e98a)
