### ISSUE TITLE
[VSCode extension]: Underline decoration not show for attribute if class use multiple selector before it

### ISSUE THREAD

**Issue by JianJroh** [unocss/unocss#3684]
### UnoCSS version

0.58.9

### Describe the bug

For ```mt-1```

**Not show**
![image](https://github.com/unocss/unocss/assets/45714701/ba853478-fcc0-49e5-afb3-72347d0faa11)

<hr />

**Show**

![image](https://github.com/unocss/unocss/assets/45714701/bc8b60ae-422f-452f-8375-e5a4ee15c3d4)

![image](https://github.com/unocss/unocss/assets/45714701/40336df1-9d86-4805-a069-7ca85bb3391c)

### Reproduction

In vscode

### System Info

vscode: 1.87.2

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
<img width="394" alt="image" src="https://github.com/unocss/unocss/assets/57086651/06edcf25-1614-43e0-bae3-ea7457b13654">

You can add a space to avoid this problem, I will try to fix it later

**Comment by Simon-He95** [comment]
@JianJroh I found that this is not a bug, it is because the `presetAttributify` plug-in is not introduced, and it supports the mode of using attributes.
[playground](http://127.0.0.1:5173/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuCBGcCm6UA7gIwkBMAfOgA4Ae6wA9OBFUA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID0DqcHEAVSptAF9QORpKTlAAcgsqJkhIaMFBYlFEGXlMC2gM2QVCFTVYdQAKSWkaHKgALlAAbR1peuimC0hESNpq6M0JUHdoPjroulRo0GCAXS8ZnUgACz5ENoE6iukYto6uxeXV6JHWEmRodVBjlD5MeHVwUCWAN3AaGsvkVkxoXp1gr19DJA6o1Nrp9IZApRSgBKLyOcGINwecpNTaQJhfcB1ACMADoAExwzZMVDwEYLUzcIEgKCcXGLYA-UHBWGogHGUyMSzWOwwnRzaTEVjwVAAFQW4E4WNApUQEql0NAAF4AHwSVFyyXgencTBMBDnJX9TgjAAc3CIE2Cv0ELMEQA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUGLSZcYAN7awYLvTgBaAO4IYAc1JwNAVgAM7gNymwAAVphZQBPMEEARhZ5awAKG1J4JDllAEofMwAjWmQAawcoLFQmK2QsZW4NOHJeGIByUvKodDFKRjEAFk9atO0AXyA&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwF8g)

**Comment by JianJroh** [comment]
> @JianJroh I found that this is not a bug, it is because the `presetAttributify` plug-in is not introduced, and it supports the mode of using attributes. [playground](http://127.0.0.1:5173/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuCBGcCm6UA7gIwkBMAfOgA4Ae6wA9OBFUA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID0DqcHEAVSptAF9QORpKTlAAcgsqJkhIaMFBYlFEGXlMC2gM2QVCFTVYdQAKSWkaHKgALlAAbR1peuimC0hESNpq6M0JUHdoPjroulRo0GCAXS8ZnUgACz5ENoE6iukYto6uxeXV6JHWEmRodVBjlD5MeHVwUCWAN3AaGsvkVkxoXp1gr19DJA6o1Nrp9IZApRSgBKLyOcGINwecpNTaQJhfcB1ACMADoAExwzZMVDwEYLUzcIEgKCcXGLYA-UHBWGogHGUyMSzWOwwnRzaTEVjwVAAFQW4E4WNApUQEql0NAAF4AHwSVFyyXgencTBMBDnJX9TgjAAc3CIE2Cv0ELMEQA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUGLSZcYAN7awYLvTgBaAO4IYAc1JwNAVgAM7gNymwAAVphZQBPMEEARhZ5awAKG1J4JDllAEofMwAjWmQAawcoLFQmK2QsZW4NOHJeGIByUvKodDFKRjEAFk9atO0AXyA&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwF8g)

I‘ve imported ```presetAttributify```.
Maybe my description is not very clear, the problem is only that the class name does not show the underline decoration in vscode.

**Comment by Simon-He95** [comment]
I understand what you mean. I updated the playground link above. You can see that the attribute at the end will be underlined.

**Comment by JianJroh** [comment]
![image](https://github.com/unocss/unocss/assets/45714701/e98e6743-5516-488d-b425-372a65a635fb)

I found it can only be reproduced in local vscode and not in playground.

**Comment by Simon-He95** [comment]
it seems that `[&_>*]:w-full` cause, I will continue to follow it when I have more time.
