### ISSUE TITLE
Selection modifier inheritance differs from TailwindCSS 

### ISSUE THREAD

**Issue by def-roth** [unocss/unocss#3767]
### UnoCSS version

0.59.4

### Describe the bug

Tailwind applies **selection:*** to all descendants while UNO does this only to the next decendant. In order to use the selection specifier you must use it on all text containing parent nodes or use a global selector.

Tailwind reference: https://tailwindcss.com/docs/hover-focus-and-other-states#highlighted-text

### Reproduction

Try the following code with tailwind and with UNO (playgrounds).

Tailwind Playground: https://playcode.io/tailwind
UNO Playground: https://unocss.dev/play/

```js 
 <div class='selection:bg-red-500 h-full py-6 px-6 bg-white'>
      <div class='bg-gray-50 shadow-lg border rounded-md'>
        <div class='mx-auto max-w-7xl py-12 px-6 lg:flex lg:items-center lg:justify-between lg:py-16 lg:px-8'>
          <h2 class='text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl'>
            <span class='block'>Hello Tailwind</span>
            <span class='block text-my-indigo'>
              Start editing to see some magic happen.
            </span>
          </h2>
          <div class='mt-8 flex lg:mt-0 lg:flex-shrink-0'>
            <div class='inline-flex rounded-md shadow'>
              <a
                href='#'
                class='inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-5 py-3 text-base font-medium text-white hover:bg-indigo-700'
              >
                Button
              </a>
            </div>
            <div class='ml-3 inline-flex rounded-md shadow'>
              <a
                href='#'
                class='inline-flex items-center justify-center rounded-md border border-transparent bg-white px-5 py-3 text-base font-medium text-indigo-600 hover:bg-indigo-50'
              >
                Button
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Fixed in #3771

See [playground](https://deploy-preview-3771--unocss.netlify.app/play/?html=AQHgJglgbsDGA2BDAzsgvAcmQU3t2ALhAPYB2AXAEYDmAtAE7Zi0CsADG8ABa0BmArvHjAADgE9aANlEAPKcBq0A7lwgFsGAHwAoYHv3hocJKkyLq9RBPbBkXRGGJLa8aguL0w2esHrF%2BpF7MALZgWrr6kYYwCCjoGMFyiPwExMDBiHLOAOwywuK0AIwATLLyruS8eDLAFWrYwci0sNik6j4VAFb8yES8EpTYBErYrbXU5AWF0hUicgAc4ZHLoFylsaYY6jIEtADMecC8ZLuUxPBgwASWsADWEKR0RNRcBFfYO7QWVrQAnBy2YLkba7AAseSWK2WIGQIkQpGMcTM8GIdy0AAlcCjgAAVRAQeBKB5gEAAelh8J0UOhFIRG3ilBRd3en2CEmJEGoxEh1MiAGUCIh6G8mGoHm5UrZRrZiMFsOlENQILBuIgRCJWgA6CK80DkuGkKm8slrI3U6KIzbBXbzI7Vcbka20TgVKofWh2egPW7OnnGyAxEzxB7wB7YPj2vwBIK0UK2eyOJR%2B3UgRA63X6LiMXiYADEGHTGctwdIodI4bdNXqjWarXawG6vQg-VrbW8vn8gSYscuZ087b7XnotGu8IpjDaCjoHK5UgBc1YogkexZpxQ8uObVjov4wVXylU6m4xCg3io08CnOItGyHALRb0ZofACEUqlSIXjaTEE-zaSA7%2BUIWvSmDBPA%2BzACGYYRh8HbRt2cZ2A4TjJsaaYPpm2Z5veGHFpgUHljBVbqDWLRtj4jZ9BIZH1lGXYhL2HhDu4-bDqOpDjnWU4HvUZQsEuEEgrQlDrkcJzbpAu77jO16SACXAnmeigyawbA4UWgG6q%2BBDvp%2Bf4-np0L-tAmkGMZUCmWSAGflZJnprZFlAA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4XyA)
