### ISSUE TITLE
[Shortcuts] Does not properly return higher priority based on the last/later entry.

### ISSUE THREAD

**Issue by phojie** [unocss/unocss#4037]
### UnoCSS version

v0.61.9 (latest) 

### Describe the bug

**html**: 
![Screenshot 2024-08-01 at 6 46 16 AM](https://github.com/user-attachments/assets/e91b0a7a-e7ff-4d28-acae-80bb321c077e)

**shotcuts config**: 
![Screenshot 2024-08-01 at 6 46 59 AM](https://github.com/user-attachments/assets/eb587e6e-1372-492e-88ad-9b427c529c48)

**OUTPUT**:
![Screenshot 2024-08-01 at 7 01 21 AM](https://github.com/user-attachments/assets/c467597e-a4c7-4d1b-82fc-d9c603bf09b1)
 
**EXPECTED OUTPUT**: 

🐞   **BG-GREEN**: It should prioritize the last shotcut configuration as it states in the documentation that `the Later entries have higher priority`. ref: https://unocss.dev/config/#shortcuts

Or did I just miss something? 🤔 

### Reproduction

[Unocss Playground Link](https://unocss.dev/play/?html=DwEwlgbgBAFgtAMwK4BsVQOYCcwigBxQEMBjAUzjABcyBbAZznIDsasA%2BAKE6ih96ihIUEsXr0AvACJ4AVgAMUAO5wFUejAD2WKiSRUAjOq069VAExSA9F34C%2BwK%2BAhcgA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDAVSraAvqDk1KnUADkFlRMkJABgoLEoogy8pgW0LGyCoQqarDqABSS0pAAFnyITFaQAFwSOtIBBUUliABMARUB2Oq0bAEO0oG1-PUAjM2BbcjqdODwXToe3U4GAhUA2lW6%2Bq5UWQCU3Y7rxqaMltZ2290Aup5bgkA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4XyA)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
This is a bit tricky tbh. Usually the order of shortcuts are decided by the rules it assigned to, and we didn't consider the order of shortcuts (only for matching not sorting).

For example, in cases [like this](https://unocss.dev/play/?html=DwEwlgbgBAFgtAMwK4BsVQOYCcwigBxQEMBjAUzjABcyBbAZznIDsasA%2BAKFEigCMA9lhBks-ISKxwAjFyhQe0EsXr0AvACJ4AVgAMUAO5w9UejCFUSSKtNPmsl6wCZ%2BGOFjIgNAei7Bv4BB%2BAZBcQA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDAVSraAvqDk1KnUADkFlRMkJABgoLEoogy8pgW0LGyCoQqarDqABSS0pAAFnyITFaQAFwSOtIBBUUliACMARUBnE0O0oG1-PUATM2BnES9AAwBHR4dTgYCFQDaVbr6rlRZAJQdjsvGpoyW1nbrHQC6nmuCQA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4XyA), `mx20` has higher priority than `m1`, because it's more specific, which ends up the shortcuts assigned to them also have different priorities that respect the priorities of the real utilities use. 

I am not very sure if there is a way to balance this and your requirements.

**Comment by phojie** [comment]
> This is a bit tricky tbh. Usually the order of shortcuts are decided by the rules it assigned to, and we didn't consider the order of shortcuts (only for matching not sorting).
> 
> For example, in cases [like this](https://unocss.dev/play/?html=DwEwlgbgBAFgtAMwK4BsVQOYCcwigBxQEMBjAUzjABcyBbAZznIDsasA%2BAKFEigCMA9lhBks-ISKxwAjFyhQe0EsXr0AvACJ4AVgAMUAO5w9UejCFUSSKtNPmsl6wCZ%2BGOFjIgNAei7Bv4BB%2BAZBcQA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDAVSraAvqDk1KnUADkFlRMkJABgoLEoogy8pgW0LGyCoQqarDqABSS0pAAFnyITFaQAFwSOtIBBUUliACMARUBnE0O0oG1-PUATM2BnES9AAwBHR4dTgYCFQDaVbr6rlRZAJQdjsvGpoyW1nbrHQC6nmuCQA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4XyA), `mx20` has higher priority than `m1`, because it's more specific, which ends up the shortcuts assigned to them also have different priorities that respect the priorities of the real utilities use.
> 
> I am not very sure if there is a way to balance this and your requirements.

Now things make sense. Thanks, @antfu
