### ISSUE TITLE
transition-colors is inconsistent with tainwindcss

### ISSUE THREAD

**Issue by canstand** [unocss/unocss#4086]
### UnoCSS version

0.62.2

### Describe the bug

`transition-colors` in UnoCSS produces: 
```css
transition-property: color,background-color,border-color,outline-color,text-decoration-color,fill,stroke;
```
There is no `outline-color` in [tainwindcss](https://tailwindcss.com/docs/transition-property). Was it intentional or an oversight?
```css
transition-property: color, background-color, border-color, text-decoration-color, fill, stroke;
```

### Reproduction

The effect of clicking the input box in the [demo](https://unocss.dev/play/?version=0.62.2&html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVgHwBQUUokUALYBDbr3F8wxAA5IMUAimG1aAXgBEVGvACcUAO6JU6MiyTEQWEHEEgoAIxZlLFR86xk4AczLCAnnAAzAAMwQ5ecBi%2BxLTSwmQk8tI4QVDSAQCMmLj4tIJ0MMIgLIZ5mNG0YBhgbIQsKE60lGDUAFxuLnBhCC1Y7RFRwjFxCaTNbdh4cGU9bQhs%2BIJWYEj50kpEMPUurZP4Pv5wAKyULARItHAQYJX2bWYYKFJYcKzsp%2BeX17dtZFIRWXmnyuNzAdz6f2IEQOAQAHKEoOBaMJwSBWucyLQnK8WPhhGgSlZETcUdQ0Sw4gQqgEjsF1Dw%2BAB6cAQbjAZmQbhAA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6smVUdAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k7pVGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWsULlQKmozkggA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4XyA)  is different from that of [shadcn (choose New York style)](https://ui.shadcn.com/docs/components/input)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
It was there before but they removed it because of it causing issues when using `focus:outline-none` together with transitions. Eg. transitioning from nothing to transparent caused a black outline to appear.

To fix a bug recently I added `text-decoration-color` and took the opportunity to add `outline-color` which was missing (completely forgetting about this issue).

The real issue though is that Tailwind mentions `focus:outline-none` in the docs when in reality there shouldn't be any outline visible at any time, so the correct class is just `outline-none`. You can see if you change `focus-visible:outline-none` to just `outline-none` that it looks correct again.

I believe `outline-color` being in `transition-colors` is correct (since well, it's a transitionable color) but I can also see that a lot of libraries (including shadcn surprisingly) use this kind of janky `focus-visible:outline-none` which causes this issue.

**Comment by henrikvilhelmberglund** [comment]
How about just adding

```css
*,
::before,
::after {
  outline-color: transparent;
}
```

to the Tailwind reset instead? This would allow for transitioning outline colors while still stopping the black border issue on focused elements that (only) use `focus:outline-none`.
