### ISSUE TITLE
[feature] recursive file scan from specific folders

### ISSUE THREAD

**Issue by samadadi** [unocss/unocss#543]
Hi. I am using unocss cli & This issue is all about adding some useful cli options.

-  add `-d --directory` option with following value formats `"folder1:folder2:..."` or `"folder1 folder2 ..."` or `[folder1,folder2,...]` .
-  add `-r --recursive` option to scan for file recursively down to the folder tree.
-  add `-e --extension` options to scan for files with specific extensions with following value formats `"*.html:*.js:*.jsx:..."` or `"*.html *.js *.jsx ..."` or `[*.html,*.js,*.jsx,...]`.

Note: I also should mention that unocss fails to create required folder recursively when it is trying to save output to a folder that does not exist.

**Comment by milesingrams** [comment]
I have a similar issue. For my Vite config I use `vite-svg-loader` to convert imports into vue components by importing using `import mySvgVueComponent from 'mySvg.svg?component'`. Unfortunately the default scanning settings cause unocss to miss these imports and the .svg file extension and therefore dont generate the classes used in the svg. This is also true for other svg preprocessing and converting packages for Vite. Being able to manually control the directory globs and extensions scanned would be very useful for these cases.

Otherwise everything is working quite smoothly with the exception of the occasional infinite loop of the web console logging `[vite] hot updated: /__uno.css`. Not sure why it happens. usually refreshing the page fixes it.

Awesome library, excited for it to become more solid and mature. I believe this approach of combining publicly created presets and using JIT is the way forwards for utility classes.

**Comment by jd-0001** [comment]
@milesingrams Try adding your SVGs in the include option and unocss will generate styles.

You can read more in [README](https://github.com/antfu/unocss#scanning)

Related issue: https://github.com/antfu/unocss/issues/166

**Comment by goldcoders** [comment]
I guess me and @samadadi  has the same features wanting on the cli 

https://github.com/antfu/unocss/issues/566#issue-1118589308

**Comment by sudongyuer** [comment]
@antfu How to solve this problem ? Is there any api suggest? I want to try this
