### ISSUE TITLE
Missing preset icon detection in VS Code

### ISSUE THREAD

**Issue by vipero07** [unocss/unocss#692]
![image](https://user-images.githubusercontent.com/4421342/157740065-16926371-c761-4dac-9863-48f661ce1e32.png)
The underline and hint popup are missing from all preset icons.

relevant vite plugin lines
![image](https://user-images.githubusercontent.com/4421342/157740473-51fcdbda-8b03-4cae-84ca-8ae5073f3654.png)

**Comment by antfu** [comment]
Yes, since loading the icons in VS Code envoriment will cause segmentfault for unkown resons, we bypassed the loading to make it works. TBH I would also think seeing the dataurl of the encoded svg is also a bit meanless, which I recommand using https://github.com/antfu/vscode-iconify as a complement.
