### ISSUE TITLE
About migrating from tailwind CSS

### ISSUE THREAD

**Issue by WangQing99** [unocss/unocss#802]
Hello,antfu, I'm sorry to disturb you.

I encountered a problem in the process of migrating the project to unocss. When using 'v-html' in the 'vue3' project, the 'class' of its wrapped content does not seem to take effect.

Maybe this is because unocss is loaded only when it is used, which is normal in tailwind projects.

```
<template>
  <div v-html="html"></div>
</template>
```
The content in html is obtained through Axios.

The above is my personal opinion. Please forgive me for my mistakes, I look forward to your reply.

**Comment by antfu** [comment]
Can you share a minimal reproduction?

**Comment by WangQing99** [comment]
Thank you for your reply.

This is a vite project I initialized to reproduce the problem：
[Here is a demo](https://github.com/WangQing99/test)

You can see that the class of the element in the container does not take effect.
![image](https://user-images.githubusercontent.com/48915604/161949806-d5fa4da3-ca6b-4c91-af1a-5e112af9cb8a.png)

You can start it with `pnpm install` then `pnpm run dev`.

**Comment by antfu** [comment]
Wondering how was that possible in TW? We generate the CSS at the build time by static analysis. While your content is fetched at runtime from a remote server, at build time we couldn't guess what' would be included in that request. If the response is known, you can provide them to the `safelist` option, otherwise, you might want to use [the Runtime](https://github.com/unocss/unocss/tree/main/packages/runtime) to generate CSS on the client side.

**Comment by WangQing99** [comment]
Thank you for your patience in answering antfu, This is because I don't understand the principle,I feel so sorry.

I solved this problem using runtime.
