### ISSUE TITLE
text-op-[xx] only works for predefined colors, not theme/custom colors

### ISSUE THREAD

**Issue by TiemenSch** [unocss/unocss#807]
The opacity modifier (text-mycolor text-op-20) doesn't work, but it does for background opacity.

https://unocss.antfu.me/?html=DwEwlgbgBARg5gWgA4CcwFsCGKCeCCcADIbIgPZIICsJALgKYAetyaWuCAxmQHa0qYAzrSgNmCCtUIA%2BAFABICpk5haOKCDL1BPAOQiA7mRQBrKLyjp1nAK7Cy6UUxHcANsdnAA9OAhzQkKSsGNh4RCTwEpQ0TuIGABaq9LEskjRyikjKquqa2uY8rupGpgVQqPQg9ABmYDyVUG4e3r7SQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEZF1tAgjDFMAEYCuMYOgCecAL5x0UCCDgByPowDGVKnIBQ61AA9IsFBgCGfADbw0mHPkLAiACgTq45SjRhUAXHADaT5y9Z6RjsAShI-ZxY3Di5eASFhUL8AXXDnKFNqL19-HzklPioYGQBaDJNUOTIkJQgTaC85SmQ5cWSUtLgYAAtUEFQvR1za%2BqhPRAj-ClBDKGFByeGCLkMirwAiAHdu4BhUdc7c5wBOAAZTjYBiAEZ0ABZDJQBmA8XxSbE-T7EQoA&options=N4IgzgLgTglgxhEAuaBXApgXyA

**Comment by chris-zhu** [comment]
Use `#fff` 、`rgb(255,255,255)`  ...  instead of `white` name, make `parseColor` function  better to parse colors
[playground](https://unocss.antfu.me/?html=DwEwlgbgBARg5gWgA4CcwFsCGKCeCCcADIbIgPZIICsJALgKYAetyaWuCAxmQHa0qYAzrSgNmCCtUIA%2BAFABICpk5haOKCDL1BPAOQiA7mRQBrKLyjp1nAK7Cy6UUxHcANsdnAA9OAhzQkKSsGNh4RCTwEpQ0TuIGABaq9LEskjRyikjKquqa2uY8rupGpgVQqPQg9ABmYDyVUG4e3r7SQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEZF1tAgjDFMAEYCuMYOgCecAL5x0UCCDgByPowDGVKnIBQ61AA9IsFBgCGfADbw0mHPkLAiACgTq45SjRhUAXHADaT5y9Z6RjsAShI-ZxY3Di5eASFhUL8AXXDnKFNqL19-HzklPioYGQBaDJNUOTIkJQgTaC85SmQ5cWSUtLgYAAtUEFQvR1za%2BqhPRAj-ClBDKGFByeGCLkMirwAiKCIeOwAmAFZ9kgOjk5D1ztznAHpruFqsFbW4dYBidA%2BLxf8ATgAGP4bV4ARnQABZDEoAMxfK7iSZiPyIsQhIA&options=N4IgzgLgTglgxhEAuaBXApgXyA)
