### ISSUE TITLE
How to use `rem` unit for preset icon scale option?

### ISSUE THREAD

**Issue by jd-0001** [unocss/unocss#842]
Hi, I want to use the `rem` unit for the icon preset's scale instead of the `em` unit.

Currently, I see no option to use `rem` instead of `em`.

**Comment by chris-zhu** [comment]
May be `extraProperties` option can help you. 
e.g.
```
{
  extraProperties: { 
    width: 1rem, 
    height: 1rem
  }
}
```
https://github.com/unocss/unocss/blob/main/packages/preset-icons/src/types.ts#L29-L35

**Comment by userquin** [comment]
@jd-0001 beware with @chris-zhu approach, you will not be able to apply custom w/h for any icon since w/h will be overriden with the `extraProperties`

The #848 will fix this: you can also use `iconCustomizer` to change w/h to all icons or apply the logic you want, check this entry https://github.com/unocss/unocss/tree/main/packages/preset-icons#iconcollection-customization

**Comment by jd-0001** [comment]
till #848 `iconCustomizer` gets resolved, I will use `iconCustomizer` approach.

I guess I should keep this issue open till PR gets merged, what do you say?

Thanks :)
