### ISSUE TITLE
Dynamic font size have lower priority than text color  ( text-[2em|2px|calc(100%-10px)] )

### ISSUE THREAD

**Issue by sondh0127** [unocss/unocss#935]
![image](https://user-images.githubusercontent.com/62163604/166724481-ece987bb-704a-40ed-92e2-f5259c677b25.png)
https://unocss.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuBTAHpgWgG0AmbAWwF0od9iYE4YAKARgAZ2BSAj9gB1wBKagCMA9gCcQ2SQVHEAzIMroAfACgoUABLY4ccVADuUuCA3AA9OAhqgA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA-6kAJRAA&options=N4IgzgLgTglgxhEAuaBXApgXyA

In windi|tailwind css I used dynamic fontsize like `text-[2em|2px|calc(100%-10px)]`, however, unocss has failed to parse it.

Expect `{font-size: 2em; }` Actual: `{color: 2em;}`

I know that there are other way to tell uno transform correctly like `text-2em`, but I still wonder if there is a better way to do it

https://github.com/unocss/unocss/blob/d6273cb4fb71d31b167437ffa019d47acd8949d9/test/__snapshots__/preset-mini.test.ts.snap#L385

https://github.com/unocss/unocss/blob/d6273cb4fb71d31b167437ffa019d47acd8949d9/test/__snapshots__/preset-mini.test.ts.snap#L386

Actual: 
https://github.com/unocss/unocss/blob/d6273cb4fb71d31b167437ffa019d47acd8949d9/packages/preset-mini/src/rules/color.ts#L15

**Comment by chu121su12** [comment]
These rules were intentional. Use unocss syntax of `text-size-x` or tailwind's jit syntax `text-[length:x]`

[Playground](https://unocss.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuBTAHpgWiTAC9sCBtAJmwFsBdKAIwHsAnEbNgpygZgAOueugB8AKChQAEtjhwWUAO7s4IccAD04CBNCRYiFBhz5KcbADsA5pgAWALhgI4MABQBGAAx0C3r0IAlIysHFw8-EIiElKy8oqYigCeLACuUIksGtqQokA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA-6kAJRAA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA)
