### ISSUE TITLE
Feature request: A more useful compilation mode

### ISSUE THREAD

**Issue by UltraCakeBakery** [unocss/unocss#948]
Now that unocss can do transforms, I am wondering how easy it would be to add support for a more useful `compilation mode` compared to the one from [windicss](https://windicss.org/posts/modes.html). One where you can also manually pick what elements get their classes and attributes combined into one.

###### EXAMPLE:

**Before:**
```html
<!-- note the additional `compile` class at the beginning -->
<div class="compile bg-red-500 text-xl font-bold border border-gray-200 dark:hover:bg-green-500 transform scale-5">
``` 
**After:**
```html
<div class="uno-2xjw9">
```

**Comment by antfu** [comment]
Well, originally I was going to say this is out-of-scope since it would be a lot of caveats to do it right (in Windi it's only supported in CLI but not the Vite plugin). But with your proposal of adding the `compile` key making it explicit, and actually becomes possible to do!

The word `compile` might be a bit too general, but I guess once we figure out a nice-looking one we could ever support it in string literals. Like (say `::uno::` for example)

```html
<script setup>
const styling = '::uno:: bg-red-500 text-xl font-bold border border-gray-200` // to be `uno-2xjw9`
</script>

<template>
  <div :class="styling">
</template>
```

I like this idea!

**Comment by antfu** [comment]
Well, originally I was going to say this is out-of-scope since it would be a lot of caveats to do it right (in Windi it's only supported in CLI but not the Vite plugin). But with your proposal of adding the `compile` key making it explicit, and actually becomes possible to do!

The word `compile` might be a bit too general, but I guess once we figure out a nice-looking one we could ever support it in string literals. Like (say `::uno::` for example)

```html
<script setup>
const styling = '::uno:: bg-red-500 text-xl font-bold border border-gray-200` // to be `uno-2xjw9`
</script>

<template>
  <div :class="styling">
</template>
```

I like this idea!

**Comment by antfu** [comment]
Implemented at #948

**Comment by UltraCakeBakery** [comment]
@antfu that was implemented very quickly. Thank you for this! I have not gotten around to testing it yet. Will do in the near future.

**Comment by MehrdadKhnzd** [comment]
I didn't find a way to make it work with Attributify. Is there a way to do that?
If not, would it be possible to have the same mechanism for that as well using the attributes' prefix?

**Comment by aleclarson** [comment]
Would someone mind explaining the benefit of this feature? Is it a CSS performance and gzip thing?

**Comment by UltraCakeBakery** [comment]
> Would someone mind explaining the benefit of this feature? Is it a CSS performance and gzip thing?

Primarily, compilation mode focuses on reducing the total amount of generated HTML. This is particularly relevant when dealing with raw storage and transfer situations where compression isn't feasible, such as statically generated HTML pages intended to be opened directly in a browser from the filesystem without needing a web server. In practical terms, this is one of the few scenarios where this optimization truly matters.

Additionally, compilation mode can obfuscate your template's markup, helping to protect your custom UI from being easily copied by other users who use UnoCSS or Tailwind.

From a performance perspective, the impact is generally minor in modern browsers, but still beneficial. Fewer classes result in less processing time required by the browser to calculate rendering and layout for each element.

Moreover, using fewer classes can slightly reduce the size of your final CSS bundle by generating fewer instances of {}.

During development, I used to quickly add this to all elements that were the root of a v-for or {#each} loop, making the DOM easier to inspect and scroll through. However, I rarely do this nowadays.

**Comment by siduck** [comment]
is it possible to make this change global? like it'd be nice to just enable it globally so user doesnt have to add `:uno:` everytime. 

Also can we reverse the class precendance? For example `btn` shortcut has bg slate and If i add a new bg class, this happens
<img width="1309" height="878" alt="Image" src="https://github.com/user-attachments/assets/c307373a-62fd-44ee-a0e0-46164bed4838" />

this behavior is useful for components where you'd want to get styles of original shortcuts overridden. but i wish instead of cancelling, cant it merge it?

i tried the transoferCompileclass() and it did the opposite...

<img width="1314" height="846" alt="Image" src="https://github.com/user-attachments/assets/f31b79fe-5487-4ded-8a48-d88e5cc1577b" />

**Comment by zyyv** [comment]
@siduck This is a new bug, could you create a new issue to track it?

**Comment by siduck** [comment]
> [@siduck](https://github.com/siduck) This is a new bug, could you create a new issue to track it?

done boss https://github.com/unocss/unocss/issues/4840
